@cellPhoneS_backend_HostAddress = http://localhost:5169
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjcxODc4ODM3LTE3YTYtNDQ1ZC1hOWE1LWM3MDAwMzkzOWE3OSIsImp0aSI6IjliN2M0NGI2LTFkZTUtNDQ1Yi05NjYwLTcxNWJmYzE3YjBiMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0IFVzZXIiLCJhbW91bnRDYXJ0IjoiMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVTRVIiLCJleHAiOjE3NzIxNzQyNTIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcxMjMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MTIzIn0.UMAJqJF8196jJ62hd9NVvg35PV4TgmZgtzTz3iIW3c8
@userId = 98a4fdb1-44a7-49d1-b9a0-03f9ff71e3c9

### Get All Categories (Paged)
GET {{cellPhoneS_backend_HostAddress}}/api/category?pageIndex=1&pageSize=5&status=active
Accept: application/json

### Get Category by ID
GET {{cellPhoneS_backend_HostAddress}}/api/category/id/1
Accept: application/json

### Get Category by Slug
GET {{cellPhoneS_backend_HostAddress}}/api/category/dien-thoai
Accept: application/json

### Create Category (Admin)
POST {{cellPhoneS_backend_HostAddress}}/api/admin/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Electronics",
  "status": "active"
}

### Update Category (Admin)
PUT {{cellPhoneS_backend_HostAddress}}/api/admin/categories/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "name": "Smartphones",
  "status": "active"
}

### Delete Category (Admin)
DELETE {{cellPhoneS_backend_HostAddress}}/api/admin/categories/1
Content-Type: application/json
Authorization: Bearer {{token}}
